global:
  resolve_timeout: 1m
  smtp_require_tls: false
receivers:
- name: c3-receiver
  webhook_configs:
  - url: http://alertmanager:9031/3.0/alertsFired
route:
  receiver: c3-receiver
  routes:
  - receiver: c3-receiver
    matchers:
    - rule_created_by="c3-1"
    repeat_interval: 876000h
    continue: true
